# train_config.base.yaml
# ----- 모델 / 경로 -----
base_model: "Qwen/Qwen2.5-1.5B-Instruct"
output_dir: "out/qwen-qlora-base"

# ----- 데이터 경로 -----
train_path: "data/train_data.jsonl"

# ----- 학습 파라미터 -----
lr: 2e-4
batch_size: 2
grad_accum: 64
epochs: 999999          # cap으로 자를거라 크게 설정
max_length: 512
max_samples: 0
max_train_steps: 20000   # mem과 동일 하드 컷
warmup_ratio: 0.03
seed: 42

# ----- LoRA -----
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - up_proj
  - down_proj
  - gate_proj

# ----- QLoRA 4bit -----
bnb_4bit_compute_dtype: "bfloat16"   # 3080이면 문제가 나면 "float16"로 변경
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: "nf4"
try_flash_attn: false

# ----- 샘플링(mem과 완전 동일) -----
use_sum_if_boundary: true         # baseline에선 의미는 없지만 통일성 위해 둠
sample_mode: pos_plus_k_neg
negatives_per_pos: 1
include_last: false
